# Generated by Django 4.2.4 on 2023-08-19 19:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OtpModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('otp', models.PositiveIntegerField()),
                ('phone_number', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message="Phone number must be 11 digit & this format: '01*********'", regex='^01[13-9]\\d{8}$')])),
            ],
            options={
                'verbose_name': 'Otp',
                'verbose_name_plural': 'Otp',
                'db_table': 'otp',
            },
        ),
    ]
